### ISSUE TITLE
multiple builders in one process, sharing cache?

### ISSUE THREAD

**Issue by mpictor** [EdSchouten/bazel-buildbarn#13]
Since I'm not running in containers, my instances generally have more than 1 cpu. Rather than running multiple worker processes _not_ sharing cache, it'd be nice to have a single process and cache, and multiple builders in that process.

How feasible would this be?

**Comment by EdSchouten** [comment]
Oomf. Turns out that this is not so trivial as I had thought. Due to an inherent race condition in UNIX, it's generally unsafe to write executables to disk from within a multi-threaded process and fork()/exec() them:

https://github.com/golang/go/issues/22315

Because I also want to make the execution strategy of `bbb_worker` a bit more pluggable and to make it easier to apply privilege separation, I am going to split off the execution into a separate coprocess, `bbb_runner`, so that we effectively work around this problem.
