### ISSUE TITLE
Support for Authentication

### ISSUE THREAD

**Issue by edbaunton** [EdSchouten/bazel-buildbarn#24]
From my understanding, currently bbb does not support authentication.

Motivation being, that in order to do prioritisation of jobs based on "who", one would need to authenticate this information. BuildGrid currently supports authentication via OAuth2 as well as custom certs. 

I think we will contribute this feature if that's ok with you.

**Comment by EdSchouten** [comment]
Perfect! Especially OAuth2(/OIDC?) support would be awesome. We also use that on our side.

I think it would be best if we first went ahead with implementing it just for bbb-frontend, so that cluster-external traffic is secured. Considering that bbb-frontend is currently a strict superset of bb(b)-storage in terms of logic, I am actually thinking about merging the two into bb(b)-storage.

I am therefore transferring this issue to bb-storage.
