### ISSUE TITLE
bazel-remote cache does not work: PUT without Content-Length

### ISSUE THREAD

**Issue by iphydf** [EdSchouten/bazel-buildbarn#6]
```
2018/09/15 12:25:44 PUT without Content-Length (key = cas/bd779c2b71151380f3ecffc672da07ec15dd98b8f4be47186e39bd7cc05c5836)
```

bazel-remote requires that Content-Length is set, so it knows how much data is going to be stored, so it can delete old files if there is not enough space.

Setting `req.ContentLength = digest.SizeBytes` doesn't seem to work reliably:
```
2018/09/15 12:28:28 Response: status:<code:2 message:"Put
 http://localhost:9090/ac/f9990c832b3d8d225e222a39dd9689bcf245f2ab45b46641b17c9f5086916b31:
 http: ContentLength=141 with Body length 257" >
```

**Comment by EdSchouten** [comment]
Setting `req.ContentLength = digest.SizeBytes` doesn't work reliably, because that's technically speaking only valid for data stored in the Content Addressable Storage (CAS). Only there the digest represents the size of the artifact. In case of the Action Cache (AC), the size in the digest corresponds to the size of the action; not the action result object that is stored.

Can you give the code in the `content-length` branch a try? Thanks!

**Comment by EdSchouten** [comment]
Just merged the `content-length` branch to `master`. Thanks for reporting!
